### ISSUE TITLE
Revive Librsync.jl using librsync_jll.jl

### ISSUE THREAD

**Issue by aminya** [JuliaBinaryWrappers/librsync_jll.jl#1]
We had a Librsync.jl which provided Julia functions for librsync. But now using librsync_jll.jl, we can simplify that library. 
https://github.com/jgoldfar/Librsync.jl

P.S: I made this issue since I could not find any other package that provides convenient Julia functions around librsync.

cc: @jgoldfar

**Comment by giordano** [comment]
1. Any issue with jll packages should be open to Yggdrasil, not here

2. I don't see what we have to do here

**Comment by aminya** [comment]
@giordano this is about Librsync and not related to Yggdrasil. Where should I discuss this?

**Comment by giordano** [comment]
Nothing? I don't understand what you want to discuss here :slightly_smiling_face:

**Comment by aminya** [comment]
😄 Maybe you are right. This might be better written in Librsync.jl.
https://github.com/jgoldfar/Librsync.jl
